apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shippingservice-deployment.yaml

images:
  - name: shippingservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/shippingservice
    newTag: latest
