apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - currencyservice-configmap.yaml
  - currencyservice-deployment.yaml

images:
  - name: currencyservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/currencyservice
    newTag: latest
