apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - recommendationservice-configmap.yaml
  - recommendationservice-deployment.yaml

images:
  - name: recommendationservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/recommendationservice
    newTag: latest
