apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - paymentservice-configmap.yaml
  - paymentservice-deployment.yaml

images:
  - name: paymentservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/paymentservice
    newTag: latest
