apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - checkoutservice-configmap.yaml
  - checkoutservice-deployment.yaml

images:
  - name: checkoutservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/checkoutservice
    newTag: latest
