apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  - common-config.yaml
  - network-policy.yaml
  - serviceaccounts.yaml
  - observability
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - emailservice
  - frontend
  - paymentservice
  - productcatalogservice
  - recommendationservice
  - shippingservice
  - redis

